name: tiny_password
description: A secure password manager built with Flutter.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # Database
  sqflite_sqlcipher: ^2.2.1
  
  # Encryption
  encrypt: ^5.0.1
  crypto: ^3.0.3
  
  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1
  
  # Biometrics
  local_auth: ^2.1.7
  
  # UI Components
  flutter_slidable: ^3.0.0
  
  # Utils
  path_provider: ^2.1.1
  uuid: ^4.0.0
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/